- name: install chrony
  apt:
    name: chrony

- name: configure chrony
  template:
    src: chrony/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: 0644
  register: chrony

- name: configure chrony defaults
  template:
    src: chrony/default.j2
    dest: /etc/default/chrony
    mode: 0644
  register: chrony_defaults

- name: create systemd dependency work-around directory for chrony
  file:
    path: /etc/systemd/system/chrony.service.d
    recurse: yes
    state: directory
  when: ansible_distribution_version == "18.04"

- name: install systemd dependency work-around for chrony
  copy:
    content: |
      [Unit]
      After=
      After=network.target network-online.target
      Wants=network-online.target
    dest: /etc/systemd/system/chrony.service.d/custom.conf
    mode: 0644
  register: chrony_custom
  when: ansible_distribution_version == "18.04"

- name: reload chrony
  systemd:
    name: chrony
    daemon_reload: yes
    enabled: yes
  when: ansible_distribution_version == "18.04" and chrony_custom.changed  # noqa no-handler

- name: restart chrony
  systemd:
    name: chrony
    state: restarted
  when: chrony.changed or chrony_defaults.changed  # noqa no-handler
