- name: install chrony
  apt:
    name: chrony

- name: configure chrony
  template:
    src: chrony/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: 0644
  register: chrony

- name: configure chrony defaults
  template:
    src: chrony/default.j2
    dest: /etc/default/chrony
    mode: 0644
  register: chrony_defaults

- name: restart chrony
  systemd:
    name: chrony
    state: restarted
  when: chrony.changed or chrony_defaults.changed  # noqa no-handler
