- name: install tinyproxy
  apt:
    name: tinyproxy
  environment: "{{ local_proxy['environment'] | default({}) }}"
  when: local_proxy is defined and local_proxy['enabled']

- name: configure tinyproxy
  template:
    src: tinyproxy/tinyproxy-focal.conf.j2
    dest: /etc/tinyproxy/tinyproxy.conf
    mode: 0644
  register: tinyproxy
  when: local_proxy is defined and local_proxy['enabled']

- name: restart tinyproxy
  service:
    name: tinyproxy
    state: restarted
    enabled: yes
  when: tinyproxy.changed  # noqa no-handler

- name: configure apt proxy
  template:
    src: apt/proxy.j2
    dest: /etc/apt/apt.conf.d/proxy
    mode: 0644
  when: local_proxy is defined and local_proxy['enabled']
