galaxy_info:
  author: Bloomberg Finance L.P.
  description: OpenStack Nova HAProxy role

  license: Apache-2.0

  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    versions:
    - bionic

dependencies:
  - role: haproxy
