###############################################################################
#  neutron
###############################################################################

neutron_config_files:
  - src: neutron-haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.d/neutron.cfg
    mode: '0644'
    notification: reload haproxy
