network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: ETH0_USE_ROUTES
    eth1:
      addresses:
        - 172.16.0.67/31
      mtu: 9000
    eth2:
      addresses:
        - 172.16.0.71/31
      mtu: 9000
