network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: ETH0_USE_ROUTES
    eth1:
      addresses:
        - 172.16.0.4/31
      mtu: 9000
    eth2:
      addresses:
        - 172.16.0.6/31
      mtu: 9000
    eth3:
      addresses:
        - 10.121.85.1/27
      mtu: 9000
