#!/bin/bash

# Copyright 2018, Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

RABBITMQCTL=/usr/sbin/rabbitmqctl

function ok {
printf "\
HTTP/1.0 200 OK\r
Content-Type: text/plain\r
Content-Length: 30\r
\r
RabbitMQ on this node is up.\r
"
}

function not_ok {
printf "\
HTTP/1.0 503 Service Unavailable\r
Content-Type: text/plain\r
Content-Length: 34\r
\r
RabbitMQ on this node is not up.\r
"
}

# Needed to prevent erlexec from failing if HOME is unset
export HOME=/var/lib/rabbitmq

if $RABBITMQCTL cluster_status > /dev/null 2>&1; then
    ok
else
    not_ok
fi
