# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright:: 2020 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

base_box = 'bento/ubuntu-18.04'
base_box_version = '202005.21.0'

def setup_proxy(node)
  http_proxy  = ENV['http_proxy']  || ''
  https_proxy = ENV['https_proxy'] || ''
  return unless http_proxy != ''
  node.vm.provision 'shell', path: 'proxyconfig.sh',
                             args: [http_proxy, https_proxy]
end

# load util module
require '../lib/util.rb'

Vagrant.configure(2) do |config|
  if ENV.key?('BCC_DEPLOY_NETWORK_VM')

    config.vm.define 'network' do |node|
      config.vm.provider 'virtualbox' do |vb|
        vb.name = Util.vbox_name('network')
        vb.memory = 512
      end
      node.vm.hostname = 'network'
      node.vm.box = base_box
      config.vm.box_version = base_box_version
      node.vm.box_download_insecure = true
      Util.mount_apt_cache(node)
      node.vm.network('private_network',
        virtualbox__intnet: Util.vbox_name('management1'),
        auto_config: false)
      node.vm.network('private_network',
        virtualbox__intnet: Util.vbox_name('management2'),
        auto_config: false)
      node.vm.network('private_network',
        virtualbox__intnet: Util.vbox_name('management3'),
        auto_config: false)
      setup_proxy(node)
      node.vm.provision 'shell', path: 'provisioner.sh', args: 'network'
    end

  else

    # Create 3 TORs
    (1..3).each do |i|
      config.vm.define "tor#{i}" do |node|
        node.vm.provider 'virtualbox' do |vb|
          vb.name = Util.vbox_name("tor#{i}")
          vb.memory = 512
        end
        node.vm.box = base_box
        config.vm.box_version = base_box_version
        node.vm.box_download_insecure = true
        Util.mount_apt_cache(node)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("tor#{i}_spine1"),
          auto_config: false)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("tor#{i}_spine2"),
          auto_config: false)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("tor#{i}_hv"),
          auto_config: false)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("management#{i}"),
          auto_config: false)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("storage#{i}"),
          auto_config: false)
        setup_proxy(node)
        node.vm.provision 'shell', path: 'provisioner.sh', args: "tor#{i}"
        node.vm.hostname = "tor#{i}"
      end
    end

    # Create 2 spines
    (1..2).each do |i|
      config.vm.define "spine#{i}" do |node|
        node.vm.provider 'virtualbox' do |vb|
          vb.name = Util.vbox_name("spine#{i}")
          vb.memory = 512
        end
        node.vm.box = base_box
        config.vm.box_version = base_box_version
        node.vm.box_download_insecure = true
        Util.mount_apt_cache(node)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("tor1_spine#{i}"),
          auto_config: false)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("tor2_spine#{i}"),
          auto_config: false)
        node.vm.network('private_network',
          virtualbox__intnet: Util.vbox_name("tor3_spine#{i}"),
          auto_config: false)
        setup_proxy(node)
        node.vm.provision 'shell', path: 'provisioner.sh', args: "spine#{i}"
        node.vm.hostname = "spine#{i}"
      end
    end
  end
end
