###############################################################################
#  heat
###############################################################################

heat_config_files:
  - src: heat-haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.d/heat.cfg
    mode: '0644'
    notification: reload haproxy
