- name: template placement haproxy config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items: "{{ placement_config_files }}"
  notify: "{{ item.notification }}"
