#!/bin/bash

# Copyright 2021, Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SERVICE="$1"

status="$(cat)"
CURL="curl -q -s"
self="{{ inventory_hostname }}"

SESSION=$($CURL "http://{{ client_address }}:8500/v1/kv/${SERVICE}/leader?consistent" | grep -E -i -o "[0-9a-z]{8}-([0-9a-z]{4}-){3}[0-9a-z]{12}")

# Find out if I am holding onto lock
LOCK_HOLDER=$($CURL "http://{{ client_address }}:8500/v1/session/info/$SESSION" | jq -r ".[] | .Node")
if [ "$LOCK_HOLDER" == "$self" ]; then
  LEADER=true
fi

echo "$status" | jq ".[] | select((.Node==\"$self\") and (.CheckID==\"service:${SERVICE}\")) | .Status" | grep -q passing
if [ $? -eq 0 ]; then
  if [ "$SESSION" == "" ]; then
    # There is no leader, attempt to lock
    SESSION=$($CURL -X PUT -d "{\"Name\": \"${SERVICE}\"}" "http://{{ client_address }}:8500/v1/session/create?consistent" | grep -E -i -o "[0-9a-z]{8}-([0-9a-z]{4}-){3}[0-9a-z]{12}")
    # If lock is acquired, mark myself as leader
    $CURL -X PUT -d "{\"Name\": \"${SERVICE}\"}" "http://{{ client_address }}:8500/v1/kv/${SERVICE}/leader?consistent&acquire=$SESSION" && LEADER=true
  fi
else
  # Failed check, so release lock if I am leader
  if [ "$LEADER" == "true" ]; then
    $CURL -X PUT "http://{{ client_address }}:8500/v1/kv/${SERVICE}/leader?release=$SESSION"
    LEADER=false
  fi
fi

# Update service tag
if [ "$LEADER" == "true" ]; then
  payload=$(cat {{ consul_config_directory }}/services.json | jq -M -c "to_entries | .[] | if .key==\"service\" then .value else .value[] | select(.name==\"${SERVICE}\") end | .tags += [\"primary\"]")
  $CURL -X PUT -d "$payload" http://{{ client_address }}:8500/v1/agent/service/register
else
  payload=$(cat {{ consul_config_directory }}/services.json | jq -M -c "to_entries | .[] | if .key==\"service\" then .value else .value[] | select(.name==\"${SERVICE}\") end")
  $CURL -X PUT -d "$payload" http://{{ client_address }}:8500/v1/agent/service/register
fi
